AllCops:
  Exclude:
    - bin/spring
    - bin/setup
    - bin/update
    - bin/yarn
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - Gemfile
    - 'lib/**/*'
    - 'bin/**/*'
    - app/models/user.rb
    - app/models/conversation.rb
    - app/models/upload.rb
    - app/models/project.rb
    - app/models/message.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - app/helpers/meta_tags_helper.rb
    - app/helpers/application_helper.rb
    - app/controllers/users_controller.rb
Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false
