AllCops:
  Exclude:
    - bin/spring
    - bin/setup
    - bin/update
    - bin/yarn
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - Gemfile
    - 'lib/**/*'
    - 'bin/**/*'

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/IndentationConsistency:
  Exclude:
    - app/models/user.rb