development:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>

production:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>

test:
  cloud_name: <%= ENV["CLOUDINARY_CLOUD_NAME"] %>
  api_key: <%= ENV["CLOUDINARY_KEY"] %>
  api_secret: <%= ENV["CLOUDINARY_SECRET"] %>
